name: publish and deploy

on:
  push:
    branches: [master]

jobs:
  read_demos:
    name: Read demos
    runs-on: ubuntu-latest
    outputs:
      demos: ${{ steps.read-demos-folder.outputs.demos }}
    env:
      HUSKY: 0
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Read demos children as JSON array
        id: read-demos-folder
        run: |
          DEMOS=$(ls demos | jq -R -s -c 'split("\n")[:-1]')
          echo ::set-output name=demos::${DEMOS}

  container-builds:
    needs:
      - read_demos
    runs-on: ubuntu-latest
    strategy:
      matrix:
        demo: ${{ fromJSON(needs.read_demos.outputs.demos) }}
    env:
      HUSKY: 0
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-${{ matrix.demo }}-cache
          key: ${{ runner.os }}-buildx-${{ matrix.demo }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.demo }}-

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image (with cache)
        uses: docker/build-push-action@v3
        with:
          context: demos/${{ matrix.demo }}
          push: true
          tags: |
            basistheory/${{ matrix.demo }}-demo:latest
            basistheory/${{ matrix.demo }}-demo:${{ github.sha }}
          build-args: |
            USE_COOKIE_SESSION=true
          cache-from: type=local,src=/tmp/.buildx-${{ matrix.demo }}-cache
          cache-to: type=local,dest=/tmp/.buildx-${{ matrix.demo }}-cache-new

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move caches
        run: |
          rm -rf /tmp/.buildx-${{ matrix.demo }}-cache
          mv /tmp/.buildx-${{ matrix.demo }}-cache-new /tmp/.buildx-${{ matrix.demo }}-cache

  deploy:
    needs:
      - read_demos
      - container-builds
    runs-on: ubuntu-latest
    strategy:
      matrix:
        demo: ${{ fromJSON(needs.read_demos.outputs.demos) }}
    env:
      HUSKY: 0
    steps:
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_OPERATIONS_CREDENTIALS }}

      - name: Deploy Reference Check
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'btops-prod-reference-check'
          images: 'basistheory/${{ matrix.demo }}-demo:latest'