name: publish and deploy

on:
  push:
    branches: [master]

jobs:
  read_demos:
    name: Read demos
    runs-on: ubuntu-latest
    outputs:
      demos: ${{ steps.read-demos-folder.outputs.demos }}
    env:
      HUSKY: 0
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Read demos children as JSON array
        id: read-demos-folder
        run: |
          DEMOS=$(ls demos | jq -R -s -c 'split("\n")[:-1]')
          echo ::set-output name=demos::${DEMOS}

  container-builds:
    needs:
      - read_demos
    runs-on: ubuntu-latest
    strategy:
      matrix:
        demo: ${{ fromJSON(needs.read_demos.outputs.demos) }}
    env:
      HUSKY: 0
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build
        uses: whoan/docker-build-with-cache-action@v5
        with:
          context: demos/${{ matrix.demo }}
          image_name: basistheory/${{ matrix.demo }}-demo
          image_tag: latest
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          push_git_tag: true
          push_image_and_stages: true
          username: ${{ secrets.DOCKERHUB_USERNAME }}

#  deploy:
#    needs:
#      - container-builds
#    runs-on: ubuntu-latest
#    env:
#      HUSKY: 0
#    steps:
#      - name: Checkout repo
#        uses: actions/checkout@v3
#
#      - name: Login via Azure CLI
#        uses: azure/login@v1
#        with:
#          creds: ${{ secrets.AZURE_OPERATIONS_CREDENTIALS }}
#
#      - name: Deploy Reference Check
#        uses: azure/webapps-deploy@v2
#        with:
#          app-name: 'btops-prod-reference-check'
#          images: 'basistheory/reference-check:${{ github.sha }}'