name: Pull Request

on:
  pull_request:
    branches: [master]

jobs:
  read_demos:
    name: Read demos
    runs-on: ubuntu-latest
    outputs:
      demos: ${{ steps.read-demos-folder.outputs.demos }}
    env:
      HUSKY: 0
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Read demos children as JSON array
        id: read-demos-folder
        run: |
          DEMOS=$(ls demos | jq -R -s -c 'split("\n")[:-1]')
          echo ::set-output name=demos::${DEMOS}

  build:
    needs:
      - read_demos
    runs-on: ubuntu-latest
    strategy:
      matrix:
        demo: ${{ fromJSON(needs.read_demos.outputs.demos) }}
    env:
      HUSKY: 0
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            :link: [Preview ${{ matrix.demo }} demo](https://stackblitz.com/github/${{ github.repository }}/tree/${{ github.head_ref }}/demos/${{ matrix.demo }})
          comment_includes: 'Preview ${{ matrix.demo }}'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-${{ matrix.demo }}-cache
          key: ${{ runner.os }}-buildx-${{ matrix.demo }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.demo }}-

      - name: Build Docker image (with cache)
        uses: docker/build-push-action@v3
        with:
          context: demos/${{ matrix.demo }}
          push: false
          tags: |
            ${{ matrix.demo }}
            ${{ matrix.demo }}:${{ github.sha }}
          build-args: |
            USE_COOKIE_SESSION=true
          outputs: type=docker,dest=/tmp/${{ matrix.demo }}.tar
          cache-from: type=local,src=/tmp/.buildx-${{ matrix.demo }}-cache
          cache-to: type=local,dest=/tmp/.buildx-${{ matrix.demo }}-cache-new

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move caches
        run: |
          rm -rf /tmp/.buildx-${{ matrix.demo }}-cache
          mv /tmp/.buildx-${{ matrix.demo }}-cache-new /tmp/.buildx-${{ matrix.demo }}-cache